### ISSUE TITLE
div II feedback

### ISSUE THREAD

**Issue by mariumtapal** [zyang2k/bluebike#1]
looking at last commit [0004495](https://github.com/zyang2k/bluebike/commit/000449527d146be5ac1153de0a0925d8d46f6259)

1. Passes `install_github`: ✅
2. Documentation builds: ✅
3. Passes R CMD check: ✅

`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`

@beanumber

**Comment by beanumber** [comment]
Your package should NOT import the `tidyverse` package. Please only import the package you actually use.
