### ISSUE TITLE
div III feedback

### ISSUE THREAD

**Issue by mariumtapal** [zyang2k/bluebike#2]
1. Passes `install_github`: ✅ 
2. Documentation builds: ✅
3. Passes R CMD check: ✅
`0 errors ✓ | 0 warnings ✓ | 0 notes ✓`
4. Results of `devtools::test()`: ✅
`[ FAIL 0 | WARN 0 | SKIP 0 | PASS 9 ]`

@beanumber

**Comment by beanumber** [comment]
You already got this on CRAN already???!? That's amazing!

Please see #3 for suggested fixes.
